projects:
  belkaapi:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\generated\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        maxDepth: 4
