/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateWaybill = `subscription OnCreateWaybill($owner: ID!, $waybillSpecId: ID!) {
  onCreateWaybill(owner: $owner, waybillSpecId: $waybillSpecId) {
    id
    owner
    team
    number
    description
    contractor
    purchaseDate
    deliveryDate
    spec {
      id
      owner
      team
      waybills {
        items {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        nextToken
      }
    }
    waybillSpecId
    products {
      items {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      nextToken
    }
    status
    createdAt
    updatedAt
    version
  }
}
`;
export const onUpdateWaybill = `subscription OnUpdateWaybill($owner: ID!, $waybillSpecId: ID!) {
  onUpdateWaybill(owner: $owner, waybillSpecId: $waybillSpecId) {
    id
    owner
    team
    number
    description
    contractor
    purchaseDate
    deliveryDate
    spec {
      id
      owner
      team
      waybills {
        items {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        nextToken
      }
    }
    waybillSpecId
    products {
      items {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      nextToken
    }
    status
    createdAt
    updatedAt
    version
  }
}
`;
export const onDeleteWaybill = `subscription OnDeleteWaybill($owner: ID!, $waybillSpecId: ID!) {
  onDeleteWaybill(owner: $owner, waybillSpecId: $waybillSpecId) {
    id
    owner
    team
    number
    description
    contractor
    purchaseDate
    deliveryDate
    spec {
      id
      owner
      team
      waybills {
        items {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        nextToken
      }
    }
    waybillSpecId
    products {
      items {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      nextToken
    }
    status
    createdAt
    updatedAt
    version
  }
}
`;
export const onCreateProduct = `subscription OnCreateProduct($owner: ID!, $productWaybillId: ID!) {
  onCreateProduct(owner: $owner, productWaybillId: $productWaybillId) {
    id
    owner
    team
    article
    name
    quantity
    unit
    cost {
      id
      owner
      team
      purchasePrice
      clientPrice
      price
      amount
      total
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    store {
      id
      owner
      team
      net
      gross
      width
      height
      length
      inStock
      dimension
      cargoPlaceNumber
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    info {
      id
      owner
      team
      images
      description
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    link {
      id
      owner
      team
      url
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    status
    waybill {
      id
      owner
      team
      number
      description
      contractor
      purchaseDate
      deliveryDate
      spec {
        id
        owner
        team
        waybills {
          nextToken
        }
      }
      waybillSpecId
      products {
        items {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        nextToken
      }
      status
      createdAt
      updatedAt
      version
    }
    productWaybillId
    createdAt
    updatedAt
    version
  }
}
`;
export const onUpdateProduct = `subscription OnUpdateProduct($owner: ID!, $productWaybillId: ID!) {
  onUpdateProduct(owner: $owner, productWaybillId: $productWaybillId) {
    id
    owner
    team
    article
    name
    quantity
    unit
    cost {
      id
      owner
      team
      purchasePrice
      clientPrice
      price
      amount
      total
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    store {
      id
      owner
      team
      net
      gross
      width
      height
      length
      inStock
      dimension
      cargoPlaceNumber
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    info {
      id
      owner
      team
      images
      description
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    link {
      id
      owner
      team
      url
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    status
    waybill {
      id
      owner
      team
      number
      description
      contractor
      purchaseDate
      deliveryDate
      spec {
        id
        owner
        team
        waybills {
          nextToken
        }
      }
      waybillSpecId
      products {
        items {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        nextToken
      }
      status
      createdAt
      updatedAt
      version
    }
    productWaybillId
    createdAt
    updatedAt
    version
  }
}
`;
export const onDeleteProduct = `subscription OnDeleteProduct($owner: ID!, $productWaybillId: ID!) {
  onDeleteProduct(owner: $owner, productWaybillId: $productWaybillId) {
    id
    owner
    team
    article
    name
    quantity
    unit
    cost {
      id
      owner
      team
      purchasePrice
      clientPrice
      price
      amount
      total
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    store {
      id
      owner
      team
      net
      gross
      width
      height
      length
      inStock
      dimension
      cargoPlaceNumber
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    info {
      id
      owner
      team
      images
      description
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    link {
      id
      owner
      team
      url
      product {
        id
        owner
        team
        article
        name
        quantity
        unit
        cost {
          id
          owner
          team
          purchasePrice
          clientPrice
          price
          amount
          total
          productId
          version
        }
        store {
          id
          owner
          team
          net
          gross
          width
          height
          length
          inStock
          dimension
          cargoPlaceNumber
          productId
          version
        }
        info {
          id
          owner
          team
          images
          description
          productId
          version
        }
        link {
          id
          owner
          team
          url
          productId
          version
        }
        status
        waybill {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        productWaybillId
        createdAt
        updatedAt
        version
      }
      productId
      version
    }
    status
    waybill {
      id
      owner
      team
      number
      description
      contractor
      purchaseDate
      deliveryDate
      spec {
        id
        owner
        team
        waybills {
          nextToken
        }
      }
      waybillSpecId
      products {
        items {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        nextToken
      }
      status
      createdAt
      updatedAt
      version
    }
    productWaybillId
    createdAt
    updatedAt
    version
  }
}
`;
export const onUpdateProductCost = `subscription OnUpdateProductCost($owner: ID!, $productId: ID!) {
  onUpdateProductCost(owner: $owner, productId: $productId) {
    id
    owner
    team
    purchasePrice
    clientPrice
    price
    amount
    total
    product {
      id
      owner
      team
      article
      name
      quantity
      unit
      cost {
        id
        owner
        team
        purchasePrice
        clientPrice
        price
        amount
        total
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      store {
        id
        owner
        team
        net
        gross
        width
        height
        length
        inStock
        dimension
        cargoPlaceNumber
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      info {
        id
        owner
        team
        images
        description
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      link {
        id
        owner
        team
        url
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      status
      waybill {
        id
        owner
        team
        number
        description
        contractor
        purchaseDate
        deliveryDate
        spec {
          id
          owner
          team
        }
        waybillSpecId
        products {
          nextToken
        }
        status
        createdAt
        updatedAt
        version
      }
      productWaybillId
      createdAt
      updatedAt
      version
    }
    productId
    version
  }
}
`;
export const onUpdateProductStore = `subscription OnUpdateProductStore($owner: ID!, $productId: ID!) {
  onUpdateProductStore(owner: $owner, productId: $productId) {
    id
    owner
    team
    net
    gross
    width
    height
    length
    inStock
    dimension
    cargoPlaceNumber
    product {
      id
      owner
      team
      article
      name
      quantity
      unit
      cost {
        id
        owner
        team
        purchasePrice
        clientPrice
        price
        amount
        total
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      store {
        id
        owner
        team
        net
        gross
        width
        height
        length
        inStock
        dimension
        cargoPlaceNumber
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      info {
        id
        owner
        team
        images
        description
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      link {
        id
        owner
        team
        url
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      status
      waybill {
        id
        owner
        team
        number
        description
        contractor
        purchaseDate
        deliveryDate
        spec {
          id
          owner
          team
        }
        waybillSpecId
        products {
          nextToken
        }
        status
        createdAt
        updatedAt
        version
      }
      productWaybillId
      createdAt
      updatedAt
      version
    }
    productId
    version
  }
}
`;
export const onUpdateProductInfo = `subscription OnUpdateProductInfo($owner: ID!, $productId: ID!) {
  onUpdateProductInfo(owner: $owner, productId: $productId) {
    id
    owner
    team
    images
    description
    product {
      id
      owner
      team
      article
      name
      quantity
      unit
      cost {
        id
        owner
        team
        purchasePrice
        clientPrice
        price
        amount
        total
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      store {
        id
        owner
        team
        net
        gross
        width
        height
        length
        inStock
        dimension
        cargoPlaceNumber
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      info {
        id
        owner
        team
        images
        description
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      link {
        id
        owner
        team
        url
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      status
      waybill {
        id
        owner
        team
        number
        description
        contractor
        purchaseDate
        deliveryDate
        spec {
          id
          owner
          team
        }
        waybillSpecId
        products {
          nextToken
        }
        status
        createdAt
        updatedAt
        version
      }
      productWaybillId
      createdAt
      updatedAt
      version
    }
    productId
    version
  }
}
`;
export const onUpdateProductLink = `subscription OnUpdateProductLink($owner: ID!, $productId: ID!) {
  onUpdateProductLink(owner: $owner, productId: $productId) {
    id
    owner
    team
    url
    product {
      id
      owner
      team
      article
      name
      quantity
      unit
      cost {
        id
        owner
        team
        purchasePrice
        clientPrice
        price
        amount
        total
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      store {
        id
        owner
        team
        net
        gross
        width
        height
        length
        inStock
        dimension
        cargoPlaceNumber
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      info {
        id
        owner
        team
        images
        description
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      link {
        id
        owner
        team
        url
        product {
          id
          owner
          team
          article
          name
          quantity
          unit
          status
          productWaybillId
          createdAt
          updatedAt
          version
        }
        productId
        version
      }
      status
      waybill {
        id
        owner
        team
        number
        description
        contractor
        purchaseDate
        deliveryDate
        spec {
          id
          owner
          team
        }
        waybillSpecId
        products {
          nextToken
        }
        status
        createdAt
        updatedAt
        version
      }
      productWaybillId
      createdAt
      updatedAt
      version
    }
    productId
    version
  }
}
`;
export const onCreateProject = `subscription OnCreateProject($owner: String!) {
  onCreateProject(owner: $owner) {
    id
    owner
    team
    managers
    accauntants
    warehousemans
    freelancers
    name
    description
    client
    status
    spec {
      id
      owner
      team
      waybills {
        items {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        nextToken
      }
    }
    createdAt
    updatedAt
    version
  }
}
`;
export const onUpdateProject = `subscription OnUpdateProject($owner: String!) {
  onUpdateProject(owner: $owner) {
    id
    owner
    team
    managers
    accauntants
    warehousemans
    freelancers
    name
    description
    client
    status
    spec {
      id
      owner
      team
      waybills {
        items {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        nextToken
      }
    }
    createdAt
    updatedAt
    version
  }
}
`;
export const onDeleteProject = `subscription OnDeleteProject($owner: String!) {
  onDeleteProject(owner: $owner) {
    id
    owner
    team
    managers
    accauntants
    warehousemans
    freelancers
    name
    description
    client
    status
    spec {
      id
      owner
      team
      waybills {
        items {
          id
          owner
          team
          number
          description
          contractor
          purchaseDate
          deliveryDate
          waybillSpecId
          status
          createdAt
          updatedAt
          version
        }
        nextToken
      }
    }
    createdAt
    updatedAt
    version
  }
}
`;
